Traceback (most recent call last):
  File "c:\Users\proig\Downloads\project\venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "c:\Users\proig\Downloads\project\venv\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\proig\Downloads\project\venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\proig\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "c:\Users\proig\Downloads\project\venv\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "c:\Users\proig\Downloads\project\venv\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\proig\Downloads\project\venv\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ydata_profiling import ProfileReport

# Generate a profile report for the dataset
profile = ProfileReport(df, title="Wine Quality Data Profiling", explorative=True)

# Save the report to an HTML file to view it in the browser
profile.to_file("wine_quality_profile.html")

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[4], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mydata_profiling[39;00m [38;5;28;01mimport[39;00m ProfileReport
[0;32m      3[0m [38;5;66;03m# Generate a profile report for the dataset[39;00m
[0;32m      4[0m profile [38;5;241m=[39m ProfileReport(df, title[38;5;241m=[39m[38;5;124m"[39m[38;5;124mWine Quality Data Profiling[39m[38;5;124m"[39m, explorative[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[1;31mModuleNotFoundError[0m: No module named 'ydata_profiling'

